spring.application.name=SPE

spring.datasource.url=jdbc:mysql://localhost:3306/chamada_escolar
spring.datasource.username=root
spring.datasource.password=gael2023

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true